spring.application.name=WebApplication


spring.security.oauth2.client.registration.google.client-id=696625909843-lqbkmi4rf2ikdvn3v67p57qhhn6e5cig.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.github.client-id=Ov23lieuvDVhKP6KrNhw
spring.security.oauth2.client.registration.github.client-secret=4a1360eddfac0741f0cc9dec2ec726278518dab4

spring.data.mongodb.uri=mongodb://localhost:27017/FarmConnect
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false



